---
- hosts: all

  tasks:

    - name: System update
      become: true
      apt: upgrade=dist update_cache=yes cache_valid_time=3600

    - name: Desktop
      become: true
      apt:
        name: ubuntu-desktop
        install_recommends: no
        update_cache: yes
        cache_valid_time: 3600

    - name: Basic packages
      become: true
      apt: name={{item}} update_cache=yes cache_valid_time=3600
      with_items:
        - gdm3
        - synaptic
        - git
        - emacs
        - gnome-terminal
        - chromium-browser

    - name: GDM config
      become: true
      lineinfile:
        dest: /etc/gdm3/custom.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: 'AutomaticLoginEnable=', line: 'AutomaticLoginEnable=True' }
        - { regexp: 'AutomaticLogin=', line: 'AutomaticLogin=vagrant' }

    - name: Auto-login lightdm
      become: true
      blockinfile:
        create: yes
        dest: /etc/lightdm/lightdm.conf
        block: |
          [SeatDefaults]
          autologin-user=vagrant

    - name: Fix screen blanking at login
      become: true
      blockinfile:
        create: yes
        dest: /etc/xdg/autostart/nodpms.desktop
        block: |
          [Desktop Entry]
          Type=Application
          Exec=xset -dpms s off s noblank s 0 0 s noexpose
          Hidden=false
          NoDisplay=false
          X-GNOME-Autostart-enabled=true
          Name[en_US]=nodpms
          Name=nodpms
          Comment[en_US]=
          Comment=

    - name: Add apps to the toolbar
      become: vagrant
      shell: export `/usr/bin/dbus-launch`; /usr/bin/gsettings set com.canonical.Unity.Launcher favorites "['application://unity-control-center.desktop', 'application://chromium-browser.desktop', 'application://gnome-terminal.desktop', 'unity://running-apps', 'application://synaptic.desktop', 'unity://expo-icon', 'unity://devices']"; kill $DBUS_SESSION_BUS_PID &> /dev/null

    - name: /etc/ansible/hosts localhost entry
      become: true
      lineinfile:
        dest: /etc/ansible/hosts
        regexp: "^localhost ansible_connection=local"
        line: "localhost ansible_connection=local"

